### ISSUE TITLE
Error : Controller not found!

### ISSUE THREAD

**Issue by bonnebulle** [youknow0/freshrss-wallabag#2]
Hello
Thanks, good extension, very usefull (for the lazy-batcher me)

When I click to the "W" button am redirected with the error "Controller not found!"
How can I do to fix it ? 
My API infos are verified twice
Maybe prmissions ?

I noticed the "W" buttn just vanish on clic when am on FreshRSS "Normal view"
( the error pop up only on "Global view"

My Fresh RSS is  ‘1.19.0-dev‘
My Wallaba is ‘2.4.2‘

It's all for me,
Thanks again

**Comment by dunkdaafunk** [comment]
Hi,

I'm having the same issue, wondering if there was a resolution?

Thanks for your work on this :-)

**Comment by philipbgm** [comment]
This problem is linked to the solution of pull request  #1 . Just change the 'c' of the subfolder 'Controller' to an uppercase 'C'. This has solved the issue for  me.

**Comment by nihir** [comment]
> This problem is linked to the solution of pull request #1 . Just change the 'c' of the subfolder 'Controller' to an uppercase 'C'. This has solved the issue for me.

This is correct, but the folder is plural so it should be 'Controllers' with the s, not the singular Controller

**Comment by bonnebulle** [comment]
Closing it, all works for now
thanks
